version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3080:80"
    depends_on:
      - nodeserver
      - client
  nodeserver:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_URL=mongodb+srv://preksha:preksha@zomato-master.9ffnz.mongodb.net/zomato?retryWrites=true&w=majority
      - GOOGLE_CLIENT_ID=1086189277168-mmr9fauprh378amam07l4e708irg1goh.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=4kl510x17JIl4W3kjsb4YNAKIAS4EIEVTZYDQLGFABPc
      - AWS_S3_ACCESS_KEY=AKIAS4EIEVTZYDQLGFAB
      - AWS_S3_SECRET_KEY=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
      - RZR_PAY_ID=rzp_test_F69U4bEQwcLV5H
      - RZR_PAY_SECRET=4Y9i44WtUlIAeUtx6O7JRvwF
      - NODE_ENV=production
      - PORT=4000
    ports:
      - "4000:4000"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
